

services:
  lambda:
    image: lambda_image
    volumes:
      - ./lambda:/function
    build: 
      context: lambda
      dockerfile: ./Dockerfile
    ports:  
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    # secrets:
    #   - AWS_ACCESS_KEY_ID
    #   - AWS_SECRET_ACCESS_KEY

# secrets:
#   AWS_ACCESS_KEY_ID:
#     file: key_id.txt
#   AWS_SECRET_ACCESS_KEY:
#     environment: ${AWS_SECRET_ACCESS_KEY}

