

services:
  lambda:
    image: lambda_image
    volumes:
      - ./lambda:/function
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:  
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}


